# Holds the list of controllers for MoveIt to use for motion planning
controller_list:
  - name: tfr_arm/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - lower_arm_joint
      - upper_arm_joint
    constraints:
      goal_time: 10.0
  - name: tfr_arm/arm_end_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - scoop_joint
    constraints:
      goal_time: 10.0