# ------------------------------------------------------------
# Limits for the encoders on our robot.
# 
#
# ------------------------------------------------------------

absolute_position_encoder_limits:
	

