# Holds all of the positions for the test client to travel to (order doesn't
# matter in this file, but this is the correct order for a dig cycle)
/positions:
  ready: [0.0, 1.65, 0.0, -0.85]
  dig: [0.0, 1.5, 0.6, -0.85]
  scoop: [0.0, 1.35, 0.9, 0.7]
  out: [0.0, 1.2, 0.9, 1.0]
  dump: [3.14159265, 0.25, 1.25, 1.1]
  release: [3.14159265, 0.21, 1.25, -0.75]
  invalid: [3.14159265, 0.5, 1.25, -0.75]
