<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="excavator">
  <!-- CHASSIS -->
  <link name="base_link" >
    <visual>
      <geometry>
        <box size="${base_length} ${tube_width} ${drivebase_total_height}"/>
      </geometry>
      <origin xyz="0 ${drivebase_beam_width / 2 + tube_width / 2} 0" />
    </visual>

    <visual>
      <geometry>
        <box size="${base_length} ${tube_width} ${drivebase_total_height}"/>
      </geometry>
      <origin xyz="0 ${-drivebase_beam_width / 2 - tube_width / 2} 0" />
    </visual>

    <!-- Front beam -->
    <visual>
      <geometry>
        <box size="${tube_width} ${drivebase_beam_width} ${drivebase_front_beam_height}"/>
      </geometry>
      <origin xyz="${base_length / 2 - tube_width / 2} 0 ${drivebase_front_beam_height / 2 - drivebase_total_height / 2}" />
    </visual>

    <!-- Rear beam -->
    <visual>
      <geometry>
        <box size="${tube_width} ${drivebase_beam_width} ${drivebase_total_height}"/>
      </geometry>
      <origin xyz="${tube_width / 2 - base_length / 2} 0 0" />
    </visual>

    <collision>
      <geometry>
        <box size="${base_length} ${tube_width} ${drivebase_total_height}"/>
      </geometry>
      <origin xyz="0 ${drivebase_beam_width / 2 + tube_width / 2} 0" />
    </collision>

    <collision>
      <geometry>
        <box size="${base_length} ${tube_width} ${drivebase_total_height}"/>
      </geometry>
      <origin xyz="0 ${-drivebase_beam_width / 2 - tube_width / 2} 0" />
    </collision>

    <!-- Front beam -->
    <collision>
      <geometry>
        <box size="${tube_width} ${drivebase_beam_width} ${drivebase_front_beam_height}"/>
      </geometry>
      <origin xyz="${base_length / 2 - tube_width / 2} 0 ${drivebase_front_beam_height / 2 - drivebase_total_height / 2}" />
    </collision>

    <!-- Rear beam -->
    <collision>
      <geometry>
        <box size="${tube_width} ${drivebase_beam_width} ${drivebase_total_height}"/>
      </geometry>
      <origin xyz="${tube_width / 2 - base_length / 2} 0 0" />
    </collision>
  </link>

  <!-- DRIVEBASE -->
  <!-- A general tread huge block: may be refined later for slightly better operational motion -->
  <link name="tread_left_link">
    <visual>
      <geometry>
        <box size="${tread_mid_length} ${tread_width} ${tread_mid_height}"/>
      </geometry>
    </visual>
  </link>

  <joint name="tread_left_joint" type="fixed">
    <parent link="base_link" />
    <child link="tread_left_link" />
    <origin xyz="0 ${(drivebase_beam_width / 2) + tube_width + (tread_width / 2)} 0" />
  </joint>

  <link name="tread_right_link">
    <visual>
      <geometry>
        <box size="${tread_mid_length} ${tread_width} ${tread_mid_height}"/>
      </geometry>
    </visual>
  </link>

  <joint name="tread_right_joint" type="fixed">
    <parent link="base_link" />
    <child link="tread_right_link" />
    <origin xyz="0 ${-(drivebase_beam_width / 2) - tube_width - (tread_width / 2)} 0" />
  </joint>

  <link name="tread_left_front_link">
    <visual>
      <geometry>
        <box size="${tread_end_length} ${tread_width} ${tread_end_height}"/>
      </geometry>
    </visual>
  </link>

  <joint name="tread_left_front_joint" type="fixed">
    <parent link="tread_left_link" />
    <child link="tread_left_front_link" />
    <origin xyz="${(tread_mid_length / 2) + (tread_end_length / 2)} 0 ${(tread_end_height / 2) - (tread_mid_height / 2)}" />
  </joint>

  <link name="tread_left_rear_link">
    <visual>
      <geometry>
        <box size="${tread_end_length} ${tread_width} ${tread_end_height}"/>
      </geometry>
    </visual>
  </link>

  <joint name="tread_left_rear_joint" type="fixed">
    <parent link="tread_left_link" />
    <child link="tread_left_rear_link" />
    <origin xyz="${-(tread_mid_length / 2) - (tread_end_length / 2)} 0 ${(tread_end_height / 2) - (tread_mid_height / 2)}" />
  </joint>

  <link name="tread_right_front_link">
    <visual>
      <geometry>
        <box size="${tread_end_length} ${tread_width} ${tread_end_height}"/>
      </geometry>
    </visual>
  </link>

  <joint name="tread_right_front_joint" type="fixed">
    <parent link="tread_right_link" />
    <child link="tread_right_front_link" />
    <origin xyz="${(tread_mid_length / 2) + (tread_end_length / 2)} 0 ${(tread_end_height / 2) - (tread_mid_height / 2)}" />
  </joint>

  <link name="tread_right_rear_link">
    <visual>
      <geometry>
        <box size="${tread_end_length} ${tread_width} ${tread_end_height}"/>
      </geometry>
    </visual>
  </link>

  <joint name="tread_right_rear_joint" type="fixed">
    <parent link="tread_right_link" />
    <child link="tread_right_rear_link" />
    <origin xyz="${-(tread_mid_length / 2) - (tread_end_length / 2)} 0 ${(tread_end_height / 2) - (tread_mid_height / 2)}" />
  </joint>

  <!-- BIN -->
  <link name="bin" >
    <visual>
      <geometry>
        <box size="${bin_length} ${bin_width} ${bin_height}" />
      </geometry>
      <origin xyz="${bin_length/2} 0 ${bin_height/2}" />
    </visual>
    <collision>
      <geometry>
        <box size="${bin_length} ${bin_width} ${bin_height}" />
      </geometry>
      <origin xyz="${bin_length/2} 0 ${bin_height/2}" />
    </collision>
  </link>
  <joint name="bin_joint" type="revolute">
    <parent link="base_link" />
    <child link="bin" />
    <axis xyz="0 -1 0" />
    <origin xyz="${-base_length/2} 0 ${base_height/2}" />
    <limit effort="1.0" velocity="1.0" lower="0" upper="${pi/4}" />
  </joint>
</robot>
